import { useState } from 'react';

import { Box, Button, TextField, CircularProgress } from '@mui/material';

import { DashboardContent } from 'src/layouts/dashboard';
import { renderIcon } from 'src/layouts/nav-config-dashboard';

import CodeDisplay from '../components/CodeDisplay';

const LiquiBaseScriptGenView = () => {
  const [isGenerating, setIsGenerating] = useState<boolean>(false);
  const [generatedLiquibase, setGeneratedLiquibase] = useState<string | null>(null);

  const handleGenerateLiquibase = () => {
    // if (!jiraId) return;
    setIsGenerating(true);
    setGeneratedLiquibase(null);

    setTimeout(() => {
      setGeneratedLiquibase(`<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog
    xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
    http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.3.xsd">

    <!-- Generated by AI-Native Change Orchestrator -->
    <changeSet id="11023-1" author="ai-orchestrator">
        <addColumn tableName="users">
            <column name="last_login" type="timestamp"/>
            <column name="preferences" type="jsonb"/>
        </addColumn>
        
        <rollback>
            <dropColumn tableName="users" columnName="last_login"/>
            <dropColumn tableName="users" columnName="preferences"/>
        </rollback>
    </changeSet>

</databaseChangeLog>`);
      setIsGenerating(false);
    }, 2000);
  };

  return (
    <DashboardContent>
      <Box className="h-full flex flex-col">
        <Box className="mb-6">
          <h2 className="text-2xl font-bold text-gray-800 flex items-center gap-1">
            {renderIcon('navbar/script-gen', 'h-4 w-4')}
            Liquibase Script Generator
          </h2>
          <p className="text-gray-600 mt-1">
            Auto-generate compliant Liquibase changeSets with built-in rollback logic.
          </p>
        </Box>

        <div className="bg-white p-4 rounded-xl shadow-sm border border-gray-200 mb-6 flex space-x-4 items-end">
          <div className="flex-1">
            <div className="relative">
              <TextField
                fullWidth
                placeholder="e.g. PLAT-1044"
                variant="outlined"
                sx={{
                  '& .MuiOutlinedInput-root': {
                    '&.Mui-focused fieldset': {
                      borderColor: 'primary.main',
                    },
                  },
                }}
              />
            </div>
          </div>
          <Button
            onClick={handleGenerateLiquibase}
            // disabled={!jiraId || isGenerating}
            variant="outlined"
            color="primary"
            sx={{
              backgroundColor: '#fff',
              textTransform: 'none',
              fontWeight: 500,
              px: 3,
              mb: 1,
              py: 1,
              '&:hover': {
                backgroundColor: 'rgba(0, 0, 0, 0.04)',
              },
            }}
            startIcon={
              isGenerating ? (
                <CircularProgress size={18} color="primary" />
              ) : (
                renderIcon('navbar/cip-gen')
              )
            }
          >
            {isGenerating ? 'Parsing Schema...' : 'Generate Script'}
          </Button>
        </div>

        {generatedLiquibase && <CodeDisplay generatedLiquibase={generatedLiquibase} />}
      </Box>
    </DashboardContent>
  );
};

export default LiquiBaseScriptGenView;
