import type React from 'react';

import { useState } from 'react';

import { Box, Typography } from '@mui/material';

import Carousel from './carousel';
import StepCard from './PhaseCard';

const mockData = {
  changeRequestNumber: 'CHG0093652',
  releaseChanges: [
    {
      jiraTicketId: 'GOMO-95',
      summary: 'Fix port-in email notification not triggering for transferred numbers',
      changeType: 'Bug Fix',
      component: 'geaurora-gomo-service',
      priority: 'High',
    },
  ],
  phases: [
    {
      phaseName: 'Preparation',
      steps: [
        {
          stepNumber: 1,
          activityDescription: 'Verify prerequisites and system health',
          stepByStepActivities: [
            'Confirm all dependent services are operational',
            'Check disk space and memory utilization',
            'Validate network connectivity to target servers',
          ],
          involvedApplicationsInfrastructure: 'Application Server, Database Server, Load Balancer',
          personInCharge: 'Yash / Developer',
          email: 'Yash.shah@example.com',
          contactNumbers: '1234567890',
          location: 'SRN',
          plannedStartDateTime: '01/01/2024, 10:00hrs',
          plannedEndDateTime: '01/01/2024, 10:30hrs',
          plannedDuration: '00:30',
          actualStartDateTime: '',
          actualEndDateTime: '',
          actualDuration: '',
          status: 'Not Started',
          comments: '',
        },
        {
          stepNumber: 2,
          activityDescription: 'Backup existing configuration and database',
          stepByStepActivities: [
            'Take backup of application configuration files',
            'Perform a full database backup',
            'Archive backups to a secure location',
          ],
          involvedApplicationsInfrastructure: 'Application Server, Database Server, Backup Storage',
          personInCharge: 'Yash / Developer',
          email: 'Yash.shah@example.com',
          contactNumbers: '1234567890',
          location: 'SRN',
          plannedStartDateTime: '01/01/2024, 10:30hrs',
          plannedEndDateTime: '01/01/2024, 11:30hrs',
          plannedDuration: '01:00',
          actualStartDateTime: '',
          actualEndDateTime: '',
          actualDuration: '',
          status: 'Not Started',
          comments: '',
        },
        {
          stepNumber: 3,
          activityDescription: 'Perform pre-deployment checks',
          stepByStepActivities: [
            'Check target server resource availability',
            'Verify deployment tool connectivity',
            'Confirm latest deployment artifact is accessible',
          ],
          involvedApplicationsInfrastructure: 'Deployment Tool, Application Server, Artifactory',
          personInCharge: 'Yash / Developer',
          email: 'Yash.shah@example.com',
          contactNumbers: '1234567890',
          location: 'SRN',
          plannedStartDateTime: '01/01/2024, 11:30hrs',
          plannedEndDateTime: '01/01/2024, 12:00hrs',
          plannedDuration: '00:30',
          actualStartDateTime: '',
          actualEndDateTime: '',
          actualDuration: '',
          status: 'Not Started',
          comments: '',
        },
      ],
    },
    {
      phaseName: 'Execution / Implementation',
      steps: [
        {
          stepNumber: 1,
          activityDescription: 'Stop application services',
          stepByStepActivities: [
            'Log in to application servers',
            'Execute stop script for all application instances',
            'Verify services are stopped',
          ],
          involvedApplicationsInfrastructure: 'Application Server, Service Manager',
          personInCharge: 'Vivek / Release Manager',
          email: 'vivek@example.com',
          contactNumbers: '2345678901',
          location: 'SRN',
          plannedStartDateTime: '01/01/2024, 12:00hrs',
          plannedEndDateTime: '01/01/2024, 12:15hrs',
          plannedDuration: '00:15',
          actualStartDateTime: '',
          actualEndDateTime: '',
          actualDuration: '',
          status: 'Not Started',
          comments: '',
        },
        {
          stepNumber: 2,
          activityDescription: 'Deploy new application build/code',
          stepByStepActivities: [
            'Trigger deployment pipeline for new artifact',
            'Monitor deployment logs for errors',
            'Confirm successful file transfer and extraction',
          ],
          involvedApplicationsInfrastructure: 'CI/CD Pipeline, Application Server, Artifactory',
          personInCharge: 'Vivek / Release Manager',
          email: 'vivek@example.com',
          contactNumbers: '2345678901',
          location: 'SRN',
          plannedStartDateTime: '01/01/2024, 12:15hrs',
          plannedEndDateTime: '01/01/2024, 12:45hrs',
          plannedDuration: '00:30',
          actualStartDateTime: '',
          actualEndDateTime: '',
          actualDuration: '',
          status: 'Not Started',
          comments: '',
        },
        {
          stepNumber: 3,
          activityDescription: 'Update database schema (if applicable)',
          stepByStepActivities: [
            'Apply database migration scripts',
            'Verify schema changes using database tools',
            'Check for any data migration issues',
          ],
          involvedApplicationsInfrastructure: 'Database Server, Database Client',
          personInCharge: 'Vivek / Release Manager',
          email: 'vivek@example.com',
          contactNumbers: '2345678901',
          location: 'SRN',
          plannedStartDateTime: '01/01/2024, 12:45hrs',
          plannedEndDateTime: '01/01/2024, 13:15hrs',
          plannedDuration: '00:30',
          actualStartDateTime: '',
          actualEndDateTime: '',
          actualDuration: '',
          status: 'Not Started',
          comments: '',
        },
        {
          stepNumber: 4,
          activityDescription: 'Update configuration files',
          stepByStepActivities: [
            'Deploy new configuration files',
            'Validate configuration parameters',
            'Restart configuration services if needed',
          ],
          involvedApplicationsInfrastructure: 'Configuration Management System, Application Server',
          personInCharge: 'Vivek / Release Manager',
          email: 'vivek@example.com',
          contactNumbers: '2345678901',
          location: 'SRN',
          plannedStartDateTime: '01/01/2024, 13:15hrs',
          plannedEndDateTime: '01/01/2024, 13:30hrs',
          plannedDuration: '00:15',
          actualStartDateTime: '',
          actualEndDateTime: '',
          actualDuration: '',
          status: 'Not Started',
          comments: '',
        },
        {
          stepNumber: 5,
          activityDescription: 'Start application services',
          stepByStepActivities: [
            'Execute start script for all application instances',
            'Monitor service startup logs',
            'Verify all application services are running',
          ],
          involvedApplicationsInfrastructure: 'Application Server, Service Manager',
          personInCharge: 'Vivek / Release Manager',
          email: 'vivek@example.com',
          contactNumbers: '2345678901',
          location: 'SRN',
          plannedStartDateTime: '01/01/2024, 13:30hrs',
          plannedEndDateTime: '01/01/2024, 13:45hrs',
          plannedDuration: '00:15',
          actualStartDateTime: '',
          actualEndDateTime: '',
          actualDuration: '',
          status: 'Not Started',
          comments: '',
        },
      ],
    },
    {
      phaseName: 'GO-Live (Post Change Verification / Sanity Checks)',
      steps: [
        {
          stepNumber: 1,
          activityDescription: 'Perform sanity checks on application UI',
          stepByStepActivities: [
            'Access application URL via browser',
            'Verify login functionality',
            'Navigate through key UI pages to confirm rendering',
          ],
          involvedApplicationsInfrastructure: 'Web Browser, Application Frontend',
          personInCharge: 'prakhar / QA Lead',
          email: 'prakhar@example.com',
          contactNumbers: '3456789012',
          location: 'SRN',
          plannedStartDateTime: '01/01/2024, 13:45hrs',
          plannedEndDateTime: '01/01/2024, 14:15hrs',
          plannedDuration: '00:30',
          actualStartDateTime: '',
          actualEndDateTime: '',
          actualDuration: '',
          status: 'Not Started',
          comments: '',
        },
        {
          stepNumber: 2,
          activityDescription: 'Verify critical business functionalities',
          stepByStepActivities: [
            'Execute predefined test cases for core features',
            'Validate data submission and retrieval',
            'Confirm integration points are working (if applicable)',
          ],
          involvedApplicationsInfrastructure:
            'Application Backend, Test Management Tool, Integrated Systems',
          personInCharge: 'prakhar / QA Lead',
          email: 'prakhar@example.com',
          contactNumbers: '3456789012',
          location: 'SRN',
          plannedStartDateTime: '01/01/2024, 14:15hrs',
          plannedEndDateTime: '01/01/2024, 15:15hrs',
          plannedDuration: '01:00',
          actualStartDateTime: '',
          actualEndDateTime: '',
          actualDuration: '',
          status: 'Not Started',
          comments: '',
        },
        {
          stepNumber: 3,
          activityDescription: 'Monitor logs for errors',
          stepByStepActivities: [
            'Review application logs for exceptions',
            'Check server logs for resource issues',
            'Monitor database logs for anomalies',
          ],
          involvedApplicationsInfrastructure: 'Logging System, Monitoring Tools',
          personInCharge: 'prakhar / QA Lead',
          email: 'prakhar@example.com',
          contactNumbers: '3456789012',
          location: 'SRN',
          plannedStartDateTime: '01/01/2024, 15:15hrs',
          plannedEndDateTime: '01/01/2024, 15:45hrs',
          plannedDuration: '00:30',
          actualStartDateTime: '',
          actualEndDateTime: '',
          actualDuration: '',
          status: 'Not Started',
          comments: '',
        },
        {
          stepNumber: 4,
          activityDescription: 'Confirm data integrity (spot checks)',
          stepByStepActivities: [
            'Perform targeted data queries post-deployment',
            'Compare sample data with expected values',
            'Ensure no data loss or corruption occurred',
          ],
          involvedApplicationsInfrastructure: 'Database Server, Data Query Tools',
          personInCharge: 'prakhar / QA Lead',
          email: 'prakhar@example.com',
          contactNumbers: '3456789012',
          location: 'SRN',
          plannedStartDateTime: '01/01/2024, 15:45hrs',
          plannedEndDateTime: '01/01/2024, 16:15hrs',
          plannedDuration: '00:30',
          actualStartDateTime: '',
          actualEndDateTime: '',
          actualDuration: '',
          status: 'Not Started',
          comments: '',
        },
      ],
    },
    {
      phaseName: 'NO-GO (Rollback/Backout plan checkpoint)',
      steps: [
        {
          stepNumber: 1,
          activityDescription: 'Restore previous application build/code',
          stepByStepActivities: [
            'Stop current application services',
            'Deploy previous stable application artifact',
            'Start previous application services',
          ],
          involvedApplicationsInfrastructure: 'CI/CD Pipeline, Application Server, Artifactory',
          personInCharge: 'ambuj / Support Engineer',
          email: 'ambuj@example.com',
          contactNumbers: '5678901234',
          location: 'SRN',
          plannedStartDateTime: '01/01/2024, 16:45hrs',
          plannedEndDateTime: '01/01/2024, 17:15hrs',
          plannedDuration: '00:30',
          actualStartDateTime: '',
          actualEndDateTime: '',
          actualDuration: '',
          status: 'Not Started',
          comments: "Executed if a 'No-Go' decision was made.",
        },
        {
          stepNumber: 2,
          activityDescription: 'Restore database from backup',
          stepByStepActivities: [
            'Stop all connections to the database',
            'Restore database from the pre-change backup',
            'Verify database restoration success',
          ],
          involvedApplicationsInfrastructure: 'Database Server, Backup System',
          personInCharge: 'ambuj / Support Engineer',
          email: 'ambuj@example.com',
          contactNumbers: '5678901234',
          location: 'SRN',
          plannedStartDateTime: '01/01/2024, 17:15hrs',
          plannedEndDateTime: '01/01/2024, 18:15hrs',
          plannedDuration: '01:00',
          actualStartDateTime: '',
          actualEndDateTime: '',
          actualDuration: '',
          status: 'Not Started',
          comments: "Executed if a 'No-Go' decision was made.",
        },
        {
          stepNumber: 3,
          activityDescription: 'Restore previous configuration files',
          stepByStepActivities: [
            'Deploy previous configuration files from backup',
            'Validate restored configuration parameters',
            'Restart configuration services if required',
          ],
          involvedApplicationsInfrastructure: 'Configuration Management System, Application Server',
          personInCharge: 'ambuj / Support Engineer',
          email: 'ambuj@example.com',
          contactNumbers: '5678901234',
          location: 'SRN',
          plannedStartDateTime: '01/01/2024, 18:15hrs',
          plannedEndDateTime: '01/01/2024, 18:30hrs',
          plannedDuration: '00:15',
          actualStartDateTime: '',
          actualEndDateTime: '',
          actualDuration: '',
          status: 'Not Started',
          comments: "Executed if a 'No-Go' decision was made.",
        },
        {
          stepNumber: 4,
          activityDescription: 'Verify previous application functionality',
          stepByStepActivities: [
            'Perform sanity checks on the rolled-back application UI',
            'Execute critical business functionality tests',
            'Review application logs for any errors post-rollback',
          ],
          involvedApplicationsInfrastructure: 'Application, Test Management Tool, Logging System',
          personInCharge: 'ambuj / Support Engineer',
          email: 'ambuj@example.com',
          contactNumbers: '5678901234',
          location: 'SRN',
          plannedStartDateTime: '01/01/2024, 18:30hrs',
          plannedEndDateTime: '01/01/2024, 19:30hrs',
          plannedDuration: '01:00',
          actualStartDateTime: '',
          actualEndDateTime: '',
          actualDuration: '',
          status: 'Not Started',
          comments: "Executed if a 'No-Go' decision was made.",
        },
        {
          stepNumber: 5,
          activityDescription: 'Confirm system stability post-rollback',
          stepByStepActivities: [
            'Monitor system resources and performance metrics',
            'Check for any unexpected behavior or alerts',
            'Declare system stable and operational on previous version',
          ],
          involvedApplicationsInfrastructure: 'Monitoring Tools, Alerting Systems',
          personInCharge: 'ambuj / Support Engineer',
          email: 'ambuj@example.com',
          contactNumbers: '5678901234',
          location: 'SRN',
          plannedStartDateTime: '01/01/2024, 19:30hrs',
          plannedEndDateTime: '01/01/2024, 20:00hrs',
          plannedDuration: '00:30',
          actualStartDateTime: '',
          actualEndDateTime: '',
          actualDuration: '',
          status: 'Not Started',
          comments: "Executed if a 'No-Go' decision was made.",
        },
      ],
    },
    {
      phaseName: 'Post Rollback/Backout Verification / Sanity Checks',
      steps: [
        {
          stepNumber: 1,
          activityDescription: 'Restore previous application build/code',
          stepByStepActivities: [
            'Stop current application services',
            'Deploy previous stable application artifact',
            'Start previous application services',
          ],
          involvedApplicationsInfrastructure: 'CI/CD Pipeline, Application Server, Artifactory',
          personInCharge: 'ambuj / Support Engineer',
          email: 'ambuj@example.com',
          contactNumbers: '5678901234',
          location: 'SRN',
          plannedStartDateTime: '01/01/2024, 16:45hrs',
          plannedEndDateTime: '01/01/2024, 17:15hrs',
          plannedDuration: '00:30',
          actualStartDateTime: '',
          actualEndDateTime: '',
          actualDuration: '',
          status: 'Not Started',
          comments: "Executed if a 'No-Go' decision was made.",
        },
        {
          stepNumber: 2,
          activityDescription: 'Restore database from backup',
          stepByStepActivities: [
            'Stop all connections to the database',
            'Restore database from the pre-change backup',
            'Verify database restoration success',
          ],
          involvedApplicationsInfrastructure: 'Database Server, Backup System',
          personInCharge: 'ambuj / Support Engineer',
          email: 'ambuj@example.com',
          contactNumbers: '5678901234',
          location: 'SRN',
          plannedStartDateTime: '01/01/2024, 17:15hrs',
          plannedEndDateTime: '01/01/2024, 18:15hrs',
          plannedDuration: '01:00',
          actualStartDateTime: '',
          actualEndDateTime: '',
          actualDuration: '',
          status: 'Not Started',
          comments: "Executed if a 'No-Go' decision was made.",
        },
        {
          stepNumber: 3,
          activityDescription: 'Restore previous configuration files',
          stepByStepActivities: [
            'Deploy previous configuration files from backup',
            'Validate restored configuration parameters',
            'Restart configuration services if required',
          ],
          involvedApplicationsInfrastructure: 'Configuration Management System, Application Server',
          personInCharge: 'ambuj / Support Engineer',
          email: 'ambuj@example.com',
          contactNumbers: '5678901234',
          location: 'SRN',
          plannedStartDateTime: '01/01/2024, 18:15hrs',
          plannedEndDateTime: '01/01/2024, 18:30hrs',
          plannedDuration: '00:15',
          actualStartDateTime: '',
          actualEndDateTime: '',
          actualDuration: '',
          status: 'Not Started',
          comments: "Executed if a 'No-Go' decision was made.",
        },
        {
          stepNumber: 4,
          activityDescription: 'Verify previous application functionality',
          stepByStepActivities: [
            'Perform sanity checks on the rolled-back application UI',
            'Execute critical business functionality tests',
            'Review application logs for any errors post-rollback',
          ],
          involvedApplicationsInfrastructure: 'Application, Test Management Tool, Logging System',
          personInCharge: 'ambuj / Support Engineer',
          email: 'ambuj@example.com',
          contactNumbers: '5678901234',
          location: 'SRN',
          plannedStartDateTime: '01/01/2024, 18:30hrs',
          plannedEndDateTime: '01/01/2024, 19:30hrs',
          plannedDuration: '01:00',
          actualStartDateTime: '',
          actualEndDateTime: '',
          actualDuration: '',
          status: 'Not Started',
          comments: "Executed if a 'No-Go' decision was made.",
        },
        {
          stepNumber: 5,
          activityDescription: 'Confirm system stability post-rollback',
          stepByStepActivities: [
            'Monitor system resources and performance metrics',
            'Check for any unexpected behavior or alerts',
            'Declare system stable and operational on previous version',
          ],
          involvedApplicationsInfrastructure: 'Monitoring Tools, Alerting Systems',
          personInCharge: 'ambuj / Support Engineer',
          email: 'ambuj@example.com',
          contactNumbers: '5678901234',
          location: 'SRN',
          plannedStartDateTime: '01/01/2024, 19:30hrs',
          plannedEndDateTime: '01/01/2024, 20:00hrs',
          plannedDuration: '00:30',
          actualStartDateTime: '',
          actualEndDateTime: '',
          actualDuration: '',
          status: 'Not Started',
          comments: "Executed if a 'No-Go' decision was made.",
        },
      ],
    },
  ],
  generatedAt: '2026-03-29T10:59:36.479065600Z',
};

const CIPPhases: React.FC<{}> = () => {
  const [phases, setPhases] = useState(mockData.phases);

  const handleUpdate = (phaseIdx: number, updatedStep: any, stepIdx: number) => {
    const updateSteps = [...phases[phaseIdx].steps];
    updateSteps[stepIdx] = updatedStep;

    const UpdatePhases = [...phases];
    UpdatePhases[phaseIdx].steps = updateSteps;

    setPhases(UpdatePhases);
  };

  return (
    <Box className="flex flex-col gap-y-4 ">
      {phases.map((data, phaseIdx) => (
        <Box>
          <Box className="mb-3 px-3">
            <Typography> {data.phaseName}</Typography>
          </Box>
          <Box className="mb-4">
            <Carousel>
              {data.steps.map((step, stepIdx) => (
                <StepCard
                  key={step.stepNumber}
                  phase={data.phaseName}
                  step={step}
                  onChange={(updated) => handleUpdate(phaseIdx, updated, stepIdx)}
                />
              ))}
            </Carousel>
          </Box>
        </Box>
      ))}
    </Box>
  );
};

export default CIPPhases;
