import { http, delay, HttpResponse } from 'msw';

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL?.trim().replace(/\/$/, '');

const SCRIPT_GENERATION_PATH = '/generate-script';

const scriptGenerationUrls = API_BASE_URL
  ? [`${API_BASE_URL}${SCRIPT_GENERATION_PATH}`, SCRIPT_GENERATION_PATH]
  : [SCRIPT_GENERATION_PATH];

const toChangeSetId = (prompt: string) =>
  prompt
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 40) || 'mock-change';

const buildMockLiquibaseScript = (prompt: string) => {
  const changeSetId = toChangeSetId(prompt);

  return [
    '-- Mock response generated by MSW',
    '-- liquibase formatted sql',
    `-- changeset mock-user:${changeSetId}`,
    `-- comment ${prompt}`,
    'ALTER TABLE users ADD COLUMN release_notes VARCHAR(255);',
    '',
    '-- rollback ALTER TABLE users DROP COLUMN release_notes;',
  ].join('\n');
};

export const handlers = scriptGenerationUrls.map((url) =>
  http.get(url, async ({ request }) => {
    const requestUrl = new URL(request.url);
    const prompt = requestUrl.searchParams.get('prompt')?.trim() ?? '';

    if (!prompt) {
      return HttpResponse.json(
        { message: 'A prompt is required to generate a Liquibase script.' },
        { status: 400 }
      );
    }

    await delay(600);

    return HttpResponse.json({
      script: buildMockLiquibaseScript(prompt),
    });
  })
);
