import { http, delay, HttpResponse } from 'msw';

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL?.trim().replace(/\/$/, '');

const httpMethods = {
  get: http.get,
  post: http.post,
  put: http.put,
  patch: http.patch,
  delete: http.delete,
} as const;

type HttpMethod = keyof typeof httpMethods;
type RouteResolver = Parameters<typeof http.get>[1];

type MockRoute = {
  method: HttpMethod;
  path: string;
  resolver: RouteResolver;
};

const resolveRouteUrls = (path: string) =>
  API_BASE_URL ? [`${API_BASE_URL}${path}`, path] : [path];

const toChangeSetId = (prompt: string) =>
  prompt
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 40) || 'mock-change';

const buildMockLiquibaseScript = (prompt: string) => {
  const changeSetId = toChangeSetId(prompt);

  return [
    '-- Mock response generated by MSW',
    '-- liquibase formatted sql',
    `-- changeset mock-user:${changeSetId}`,
    `-- comment ${prompt}`,
    'ALTER TABLE users ADD COLUMN release_notes VARCHAR(255);',
    '',
    '-- rollback ALTER TABLE users DROP COLUMN release_notes;',
  ].join('\n');
};

const routes: MockRoute[] = [
  {
    method: 'get',
    path: '/generate-script',
    resolver: async ({ request }) => {
      const requestUrl = new URL(request.url);
      const prompt = requestUrl.searchParams.get('prompt')?.trim() ?? '';

      if (!prompt) {
        return HttpResponse.json(
          { message: 'A prompt is required to generate a Liquibase script.' },
          { status: 400 }
        );
      }

      await delay(600);

      return HttpResponse.json({
        script: buildMockLiquibaseScript(prompt),
      });
    },
  },
  {
    method: 'get',
    path: '/data/jira/available',
    resolver: async () => {
      await delay(250);

      return HttpResponse.json({
        tickets: [
          'GOMO-95',
          'GOMO-96',
          'GOMO-97',
          'GOMO-98',
          'GOMO-99',
          'GOMO-100',
          'GOMO-101',
          'GOMO-102',
        ],
      });
    },
  },
  {
    method: 'get',
    path: '/data/confluence/available',
    resolver: async () => {
      await delay(250);

      return HttpResponse.json({
        pages: [
          'CONF-2001',
          'CONF-2002',
          'CONF-2003',
          'CONF-2004',
          'CONF-2005',
          'CONF-2006',
          'CONF-2007',
        ],
      });
    },
  },
];

export const handlers = routes.flatMap(({ method, path, resolver }) => {
  const registerRoute = httpMethods[method];

  return resolveRouteUrls(path).map((url) => registerRoute(url, resolver));
});
